name: CI runtime_parameters
on:
  push:
    branches:
      - '**'
    paths-ignore:  # Ignore la CI si la seule modif provient de results.csv si elles viennent de l'action
      - 'output/results.csv'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip-ci')" # Ignore les commits qui ont 'skip-ci' dans le message
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
          token: ${{ secrets.REPTOKEN }}

      - name: Build Docker image
        run: |
          docker build -t runtime_parameter .

      - name: Create output folder
        run: |
          mkdir -p output/

      - name: Adjust output folder permissions
        run: |
          chmod 777 output

      - name: Run Docker container and save output
        run: |
          docker run -v $(pwd)/output:/app/output:rw runtime_parameter


      - name: Add and Commit results.csv
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name "arnolec"
          git add $(pwd)/output/results.csv
          git commit -m "Update results.csv with Docker output [skip-ci]"

      - name: Push changes to the variation branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.REPTOKEN }}
          branch: ${{ github.ref }} # Cible la branche variation
          force: true